repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/terraform-docs/terraform-docs
    rev: "v0.15.0"
    hooks:
      - id: terraform-docs-go
        name: "Main terraform module docs"
        files: "^aws/terraform/modules/metaflow/"
        args: ["-c", "aws/terraform/modules/metaflow/.terraform-docs.yml", "markdown", "aws/terraform/modules/metaflow"]
      - id: terraform-docs-go
        name: "Computation terraform module docs"
        files: "^aws/terraform/modules/metaflow/"
        args: ["-c", "aws/terraform/modules/metaflow/modules/.terraform-docs.yml", "markdown", "aws/terraform/modules/metaflow/modules/computation"]
      - id: terraform-docs-go
        name: "Datastore terraform module docs"
        files: "^aws/terraform/modules/metaflow/"
        args: ["-c", "aws/terraform/modules/metaflow/modules/.terraform-docs.yml", "markdown", "aws/terraform/modules/metaflow/modules/datastore"]
      - id: terraform-docs-go
        name: "Metadata Service terraform module docs"
        files: "^aws/terraform/modules/metaflow/"
        args: ["-c", "aws/terraform/modules/metaflow/modules/.terraform-docs.yml", "markdown", "aws/terraform/modules/metaflow/modules/metadata-service"]
      - id: terraform-docs-go
        name: "Step Functions terraform module docs"
        files: "^aws/terraform/modules/metaflow/"
        args: ["-c", "aws/terraform/modules/metaflow/modules/.terraform-docs.yml", "markdown", "aws/terraform/modules/metaflow/modules/step-functions"]
      - id: terraform-docs-go
        name: "UI terraform module docs"
        files: "^aws/terraform/modules/metaflow/"
        args: ["-c", "aws/terraform/modules/metaflow/modules/.terraform-docs.yml", "markdown", "aws/terraform/modules/metaflow/modules/ui"]
